name: Run Python Script and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'  # 每三天运行一次

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py

    - name: Get current timestamp
      id: timestamp
      run: echo "now=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Check if debug log exists
      id: check_log
      run: |
        if [ -f "./debug.log" ]; then
          echo "log_exists=true" >> $GITHUB_ENV
        else
          echo "log_exists=false" >> $GITHUB_ENV
        fi

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.now }}
        release_name: Release ${{ env.now }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Result JSON
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.now }}
        asset_path: ./categorized_results.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Debug Log
      if: env.log_exists == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.now }}
        asset_path: ./debug.log
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
